<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonShowTextbox</name>
   <tag></tag>
   <elementGuidId>e876fcbf-b475-4348-bad2-40ff17f6ad62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#show-textbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='show-textbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73c53085-70f0-4234-b4f9-ef60ebcf837b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show-textbox</value>
      <webElementGuid>e6213fe6-d17d-4164-b468-3f9200318137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-style class2</value>
      <webElementGuid>1dbc1e03-400b-4295-b390-f99d75973506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Show</value>
      <webElementGuid>bab38025-a8d0-4404-b68e-e94b44f01dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showElement()</value>
      <webElementGuid>439f8a82-4703-4161-84d3-41d09ca82433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>045afde4-449c-429b-a317-a0838403fe9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show-textbox&quot;)</value>
      <webElementGuid>9b10fd9e-f2d9-4998-8e4f-07fc41dcd403</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='show-textbox']</value>
      <webElementGuid>8f6104b5-b4ca-4fae-908f-6bd9d752e2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/input[2]</value>
      <webElementGuid>988912e5-8c29-47a6-8dea-463e0483a37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'show-textbox' and @type = 'submit']</value>
      <webElementGuid>0d890b72-afc6-4871-a17c-95589c57aa67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
