<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonHideTextbox</name>
   <tag></tag>
   <elementGuidId>65900d32-e5e4-4ff5-9939-6e88da401f0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hide-textbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hide-textbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86f7ea5f-c6f5-4779-ba27-4186ddb40d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hide-textbox</value>
      <webElementGuid>889adfc0-abe1-44de-9cf8-869019a7d4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-style class2</value>
      <webElementGuid>75b40598-144c-4d0f-b4b3-d168a16f6482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Hide</value>
      <webElementGuid>9d722421-ff9e-49da-ac5a-ca6f60d3c786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>hideElement()</value>
      <webElementGuid>4c9c5d72-6ff0-4203-aee2-977eb0e3066e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>879204c6-0ec9-40c2-93d7-adaae664a5c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hide-textbox&quot;)</value>
      <webElementGuid>57dcb6d6-a5d1-4d8a-96d9-cfd91e4404e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hide-textbox']</value>
      <webElementGuid>9ba869fd-5a56-44bc-8038-e3c94b0282f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/fieldset/input</value>
      <webElementGuid>4a397827-2917-4be2-a14f-a6dbbca21770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'hide-textbox' and @type = 'submit']</value>
      <webElementGuid>6415dc0f-7b51-4908-940c-3293b42805e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
