<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_show-hide</name>
   <tag></tag>
   <elementGuidId>a68214f2-882d-41ff-ba03-a6f4f5603da6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='displayed-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#displayed-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d11c6737-a170-4c07-9b77-1f3c25b39d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>displayed-text</value>
      <webElementGuid>0df9779d-a24c-4311-be04-38ea4be8f80d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>show-hide</value>
      <webElementGuid>0f727790-81aa-42de-aa6a-770ef94c6912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputs displayed-class</value>
      <webElementGuid>2ead23fd-0f59-4ecf-978a-db53ee553042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Hide/Show Example</value>
      <webElementGuid>d61928aa-df1c-4f34-b875-4cee0adc84da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>598e7539-d160-464f-80b1-f809412eacdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;displayed-text&quot;)</value>
      <webElementGuid>f262d657-a024-43b6-9a4b-0552975d19de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='displayed-text']</value>
      <webElementGuid>5b90ef87-8e26-4329-9dff-11bf37ef7615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/input[3]</value>
      <webElementGuid>febaf05d-223c-4536-84b7-6b5932d6dd9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'displayed-text' and @name = 'show-hide' and @placeholder = 'Hide/Show Example' and @type = 'text']</value>
      <webElementGuid>092512d4-86d6-43ae-83d8-0f944b13deea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
