<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio1_radioButton</name>
   <tag></tag>
   <elementGuidId>26c8127d-af3b-4e79-abb3-8d4beef66532</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;radioButton&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='radioButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ddcbff3-a4f4-4f51-858c-45b8c123b555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>radio1</value>
      <webElementGuid>27951fc0-6153-4bc5-9af4-149eed0495f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radioButton</value>
      <webElementGuid>ea1192fd-30d8-4fa0-bd74-c6bc4c3dacc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radioButton</value>
      <webElementGuid>81ef47e0-9f4c-4159-b86d-29983ca1738f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>fae5a0ab-c0fc-4b6f-83ef-bb0f85e4d9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-btn-example&quot;)/fieldset[1]/label[1]/input[@class=&quot;radioButton&quot;]</value>
      <webElementGuid>b4efa341-aa20-4cf7-a3c9-b08a536d0edd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='radioButton']</value>
      <webElementGuid>9c75dd3b-84e6-4576-99c2-1762411165dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radio-btn-example']/fieldset/label/input</value>
      <webElementGuid>d1028c61-d87e-419a-9ad4-4e0c51759f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>96cdaf9d-9d6e-4b3d-a577-6bbe9f1938e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'radioButton' and @type = 'radio']</value>
      <webElementGuid>6b29ac5f-f1a7-4b26-8347-808c84f8d9f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
