<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputhide-textbox</name>
   <tag></tag>
   <elementGuidId>a04ad049-7acf-437d-af63-8b30473ea200</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hide-textbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hide-textbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5e92640-0974-4577-8da9-b3d0214b9103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hide-textbox</value>
      <webElementGuid>f93a2135-0eb9-4203-9c7a-1c6c63e4da1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-style class2</value>
      <webElementGuid>e81a5b73-1d30-4385-9fdf-f8971acaccc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Hide</value>
      <webElementGuid>ce578b3a-40a9-4c5b-9bbf-82712d745df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>hideElement()</value>
      <webElementGuid>db46332f-7668-4788-8a41-ec1215aeb701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>64d07e0e-9ea4-4b98-8920-cfa33d149b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hide-textbox&quot;)</value>
      <webElementGuid>191cf3c3-b72b-4de6-9c32-39fc84cbf187</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hide-textbox']</value>
      <webElementGuid>454c575e-dad1-4d23-919a-401537dfa529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/fieldset/input</value>
      <webElementGuid>7e89fa6d-8d7c-4fb6-bd17-72d836975ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'hide-textbox' and @type = 'submit']</value>
      <webElementGuid>45f70197-759b-4cdc-b615-1965894d020d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
