<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputshow-textbox</name>
   <tag></tag>
   <elementGuidId>af1ec7d0-0468-4ef4-8578-9e8ce1e8ac31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='show-textbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#show-textbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>520efd98-3db4-46d0-9378-443b703fdd0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show-textbox</value>
      <webElementGuid>bf770060-8188-4ccd-b1dd-0b1fa1b3cc36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-style class2</value>
      <webElementGuid>f0c4e8d2-5393-4aee-895a-29c14a9916d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Show</value>
      <webElementGuid>62fd9f51-aa1b-42d9-8f65-fa35848b69a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showElement()</value>
      <webElementGuid>78711887-f6a2-4e84-8f32-fd62b765f5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ba71cfa4-d662-4da7-bade-44071d7183ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;show-textbox&quot;)</value>
      <webElementGuid>967b1ee3-f1ab-44c4-a830-cc6d84c03a5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='show-textbox']</value>
      <webElementGuid>3178c01a-afaf-4529-a745-0f59a3d9375f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/input[2]</value>
      <webElementGuid>97617d37-9d77-49ec-95c9-6bb5e8cf92b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'show-textbox' and @type = 'submit']</value>
      <webElementGuid>27f59083-2e7a-4e04-8875-612c22d08df6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
