<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textBoxHideShowExample</name>
   <tag></tag>
   <elementGuidId>e51b4b24-f93d-4881-b564-27c22e09c198</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#displayed-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='displayed-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f645c96-d7cf-4f45-91fa-42c06d419b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>displayed-text</value>
      <webElementGuid>fe48003e-9e2b-422b-9963-319ff32187c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>show-hide</value>
      <webElementGuid>d9a20d30-26bf-4b1e-a89f-1e12487e89ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputs displayed-class</value>
      <webElementGuid>6c5b3372-df7d-4a40-bc11-feb543c2a997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Hide/Show Example</value>
      <webElementGuid>f49b043c-8bee-40d6-974d-8e5c4fa40c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97c4de39-1246-419a-bf51-e2ae88187bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;displayed-text&quot;)</value>
      <webElementGuid>d7fab037-d2fc-4e0e-90eb-c7328d3e5689</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='displayed-text']</value>
      <webElementGuid>e33c0d10-0c5a-4185-bac3-f575fdf4bf50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/input[3]</value>
      <webElementGuid>48408fdf-5dd6-4600-b6de-1a9d39b4d9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'displayed-text' and @name = 'show-hide' and @placeholder = 'Hide/Show Example' and @type = 'text']</value>
      <webElementGuid>ff62026d-0549-429e-baf5-580f499f540a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
